markdown: redcarpet
redcarpet:
  extensions: ["highlight", "tables", "with_toc_data",  "underline", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

encoding: UTF-8
name: 涧水潺湲
description: 不知者众，唯学而已

sass:
  sass_dir: assets/css/_sass
  style: :compressed

url: #
permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: #

ga_id: #
ga_username: #


timezone: Asia/Shanghai